apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kuberag
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - port: 9092
      name: plaintext
      targetPort: 9092
    - port: 9093
      name: controller
      targetPort: 9093
